mcoblenz/Obsidian

- src/main/scala/edu/cmu/cs/obsidian/codegen/CodeGen.scala
- src/main/scala/edu/cmu/cs/obsidian/parser/AST.scala
This fixes issue #99, by adding a default constructor to main contracts which don't have one already defined, and by not generating the `invokeConstructor()` method on non-main contracts, since they don't need it and can use the base-class implementation that does nothing.
> Generate default constructor for main contracts that don't have one

- build.sbt
- src/main/scala/edu/cmu/cs/obsidian/Main.scala
Fixes #123 by having the compiler return `2` when there was an error parsing arguments, and `1` when there was an error compiling the program. This will make it easier for us to test whether or not compilation succeeded.
> Return more meaningful exit codes.

- src/main/scala/edu/cmu/cs/obsidian/codegen/CodeGen.scala
When state fields were pulled to the top level, an issue arose in code generation where the code still referenced the fields inside the inner class. This error arose during state transitions, so I changed it from referring to the (non existent) state fields to assigning the top level field.
Example error:
`obs_output/generated_java/edu/cmu/cs/obsidian/generated_code/Bid.java:21: error: cannot find symbol
__stateAvailable.timeAvailable = expirationDate;
^
symbol:   variable timeAvailable
location: variable __stateAvailable of type Bid.State_Available
1 error
javac exited with value 1`
> Fix state transition issue

- Obsidian Runtime/src/Runtime/edu/cmu/cs/obsidian/client/ChaincodeClientBase.java
- Obsidian Runtime/src/Runtime/edu/cmu/cs/obsidian/client/ChaincodeClientConnectionManager.java
- Obsidian Runtime/src/Runtime/edu/cmu/cs/obsidian/java-utilities/System.obs
- build.sbt
- obstest.pl
- resources/tests/IntContainerClient.obs
- resources/tests/TestIntContainer.obstest
This script reads in `.obstest` files which are specified like this:
```
server1: file1.obs
server2: file2.obs
client: client.obs
***
expected output
```
It locates these files relative to the location of the obstest script, then compiles each of the files, compiling the `client` contract with the `--build-client` flag. It forks off processes to run each non-client 
process on a different port, then passes each one to the client (on the command line, for now), and checks that the output of the client matches what's specified in the file using `diff`.
It's written in Perl. I think it was easier than trying to parse text files using bash...
This is just a first pass at this script -- it might want to support changing the port number, and it doesn't yet support running these things on the …
> First pass at obstest script. (#73)

- resources/case_studies/Insurance/Bank.obs
- resources/case_studies/Insurance/Bid.obs
- resources/case_studies/Insurance/BidTokenPair.obs
- resources/case_studies/Insurance/InsuranceClient.obs
- resources/case_studies/Insurance/InsuranceService.obs
- resources/case_studies/Insurance/Insurer.obs
- resources/case_studies/Insurance/Money.obs
- resources/case_studies/Insurance/Token.obs
- resources/tests/parser_tests/InvokableSpec.obs
- resources/tests/parser_tests/StateInitialization.obs
- resources/tests/type_checker_tests/Assignment.obs
- resources/tests/type_checker_tests/CheckFields.obs
- resources/tests/type_checker_tests/Dereference.obs
- resources/tests/type_checker_tests/EndsInState.obs
- resources/tests/type_checker_tests/EndsInStateUnion.obs
- resources/tests/type_checker_tests/MaybeDroppedResource.obs
- resources/tests/type_checker_tests/Resources.obs
- resources/tests/type_checker_tests/Return.obs
- resources/tests/type_checker_tests/StateInitialization.obs
- src/main/scala/edu/cmu/cs/obsidian/parser/AST.scala
- src/main/scala/edu/cmu/cs/obsidian/parser/Parser.scala
- src/main/scala/edu/cmu/cs/obsidian/protobuf/ProtobufGen.scala
- src/main/scala/edu/cmu/cs/obsidian/typecheck/AstTransformer.scala
- src/main/scala/edu/cmu/cs/obsidian/typecheck/Checker.scala
- src/main/scala/edu/cmu/cs/obsidian/typecheck/Error.scala
- src/main/scala/edu/cmu/cs/obsidian/typecheck/ObsidianType.scala
- src/test/scala/edu/cmu/cs/obsidian/tests/TypeCheckerTests.scala
Add @ notation to constructors, i.e. `owned C() {...}` becomes `C@Owned() {...}` and `C() ends in S {...}` becomes `C@S() {...}`. Refactored some things in the checker as well - `InvokableDeclarations` no longer have an `endsInState` field; instead, the type is constructed while parsing.
This eliminates the need for `simpleOf` and `simpleOfWithStateNames` in the type checker, which were helpers to construct these types. These functions were basically copied to `parseTransDecl` to create fields `thisType` (which is the type the transaction is available in) and `thisFinalType` (which is the type the transaction ends in). 
There was already a mechanism to extract a type based on the permission within parsing, so I used that for extracting the type of the constructor.
Since the syntax …
> Add @ notation to constructors.

- Obsidian Runtime/src/Runtime/edu/cmu/cs/obsidian/chaincode/ChaincodeBaseMock.java
- Obsidian Runtime/src/Runtime/edu/cmu/cs/obsidian/chaincode/HyperledgerChaincodeBase.java
- Obsidian Runtime/src/Runtime/edu/cmu/cs/obsidian/chaincode/NoSuchTransactionException.java
- Obsidian Runtime/src/Runtime/edu/cmu/cs/obsidian/chaincode/ObsidianChaincodeBase.java
- buildscript/build.gradle
- src/main/scala/edu/cmu/cs/obsidian/Main.scala
- src/main/scala/edu/cmu/cs/obsidian/codegen/CodeGen.scala
So it turned out we basically already supported invoking transactions from the command line, but there was still some cleanup-type stuff to do:
Also, I added code to make it reject when the provided transaction name doesn't match any transaction. This is prevented by the compiler when you compile the client, but there was no runtime check, which meant that you wouldn't get an error when running a nonexistent transaction from the command line. This will also presumably come in handy if people want to only write their chaincode in Obsidian, and interface with it some other way.
(I also had to add handling for this to the mock-chaincode mode, but that will probably never actually be an issue.)
> Improve handling of transaction invocations (#131)

- Obsidian Runtime/src/Runtime/edu/cmu/cs/obsidian/chaincode/HyperledgerChaincodeBase.java
- buildscript/startfabric.sh
Apparently I forgot to make a pull request for this.
`-a` is now called `chaincode_archive`, which is clearer. But we'll probably remove this eventually as well once we actually get some sort of serialization to the blockchain.
Fixes #150 .
> Don't generate -a file.

- src/main/scala/edu/cmu/cs/obsidian/parser/Parser.scala
I'm not 100% sure that this is the best way to accomplish this, but it wouldn't let me put the `failure` inside the `^^ { }` function, and this way does seem to work. Do let me know if there's a more idiomatic-Scala-parser-library way to do it, though.
> Give a better error message when trying to assign a field in class body

- resources/tests/parser_tests/AvailableInRepeats.obs
- resources/tests/parser_tests/ValidTransactions.obs
- resources/tests/type_checker_tests/MultistateFields.obs
- resources/tests/type_checker_tests/ReadOnlyState.obs
- src/main/scala/edu/cmu/cs/obsidian/codegen/CodeGen.scala
- src/main/scala/edu/cmu/cs/obsidian/parser/AST.scala
- src/main/scala/edu/cmu/cs/obsidian/parser/Parser.scala
- src/main/scala/edu/cmu/cs/obsidian/parser/StateFieldTransformer.scala
- src/main/scala/edu/cmu/cs/obsidian/parser/SymbolTable.scala
- src/main/scala/edu/cmu/cs/obsidian/protobuf/ProtobufGen.scala
- src/main/scala/edu/cmu/cs/obsidian/typecheck/AstTransformer.scala
- src/main/scala/edu/cmu/cs/obsidian/typecheck/Checker.scala
- src/main/scala/edu/cmu/cs/obsidian/typecheck/Error.scala
- src/main/scala/edu/cmu/cs/obsidian/typecheck/ObsidianType.scala
- src/test/scala/edu/cmu/cs/obsidian/tests/ParserTests.scala
- src/test/scala/edu/cmu/cs/obsidian/tests/TypeCheckerTests.scala
Added support for "this" arguments that have no permission specified, in which case ReadOnlyState is inferred. "this" arguments that are missing are still treated as Shared. 
This change includes a few small improvements that I made along the way, including removal of the availableIn field from transactions and a fix to the parser to no longer use "THIS" as a contract name.
> Issue 157: ReadOnlyState support

- resources/tests/type_checker_tests/Branching.obs
- resources/tests/type_checker_tests/UnownedReference.obs
- src/main/scala/edu/cmu/cs/obsidian/typecheck/Checker.scala
- src/main/scala/edu/cmu/cs/obsidian/typecheck/Error.scala
- src/test/scala/edu/cmu/cs/obsidian/tests/TypeCheckerTests.scala
Fixes the issue of invoking a transaction (or constructor) on an Owned reference and taking ownership, even if the transaction specifies that it only needs an Unowned reference. 
Also addresses `throw` as a return statement issue.
> Issue 176 and 179

- resources/tests/type_checker_tests/InState.obs
- src/main/scala/edu/cmu/cs/obsidian/typecheck/Checker.scala
- src/test/scala/edu/cmu/cs/obsidian/tests/TypeCheckerTests.scala
We add a different context that expands the Owner states into all possible states and removes the one state we checked for in the true branch context. This fixes #206
> Fixes #206 by adding context for false branch in IfInState TypeChecker

- resources/tests/type_checker_tests/InState.obs
- src/main/scala/edu/cmu/cs/obsidian/typecheck/Checker.scala
- src/main/scala/edu/cmu/cs/obsidian/typecheck/Error.scala
- src/test/scala/edu/cmu/cs/obsidian/tests/TypeCheckerTests.scala
Fixes #192 by checking if the only possible state to transition to is the one that is being checked on. If so, log an error. Also added test cases.
> Add check for redundant if in state in typechecker and add tests

- src/main/scala/edu/cmu/cs/obsidian/Main.scala
Fixes #116. Checks if multiple contracts have the same name, and if so, stops the compiling with an error message indicating the name of the culprit contract.
> Added check for duplicate contract

- network-framework/channel-artifacts/README.md
- network-framework/docker-compose-cli.yaml
- network-framework/up.sh
The previous docker-compose-cli.yaml file had an issue which sometimes caused the peer nodes to crash (on my computer, Ubuntu 18.04.2 LTS) due to a DNS issue. This error can be fixed by forcing Go to always use the pure Go resolver (see discussion here: https://jira.hyperledger.org/browse/FAB-5822).
Additionally, it appears that installing Fabric no longer creates a fabric-samples directory, and instead puts the files directly into `.bin/`; `up.sh` has been updated accordingly.
Removing the space between the `-i` flag and `.backup` (see [here](https://github.com/mcoblenz/Obsidian/blob/afec0702830dca2ac6442aa8fd5d8d9b23b2b195/network-framework/up.sh#L89)) fixed an error (unrecognized command) on my computer.
Finally, adding the `channel-artifacts/` directory to the repository (via adding a …
> Fix setup for deploying chaincode to Fabric 

- src/main/scala/edu/cmu/cs/obsidian/typecheck/Error.scala
This pull request changes the message for mismatching types in transaction parameters from:
```
TestWrongType.obs 13.9: Found type 'C@S2' as an argument to 'f', but the argument 'x' is expected something of type 'C@S1'.
```
to:
```
TestWrongType.obs 13.9: Found type 'C@S2' as an argument to 'f', but the argument 'x' expects something of type 'C@S1'.
```
This closes #165.
> Fix grammatical mistake in type mismatch error message

- src/main/scala/edu/cmu/cs/obsidian/typecheck/ObsidianType.scala
The compiler used to crash on some redundant state checks, after this fix it will simply emit the error as originally intended. For example, compiling the following code:
```
main contract C { 
state S1 {
B@S1 b;
}   
C@S1() { ->S1; }
transaction f(C@S1 this) returns int {
if (b in S1) {
return 1;
} else {
return 2;
}
}   
}
contract B { 
state S1; 
B@S1() { ->S1; }
}
```
gives:
```
Found 1 errors:
test.obs 9.13: State check will always pass/fail. Remove redundant code.
```
This closes #232.
> Fix crash on redundant state check

- src/main/scala/edu/cmu/cs/obsidian/codegen/CodeGen.scala
- src/main/scala/edu/cmu/cs/obsidian/lexer/Lexer.scala
- src/main/scala/edu/cmu/cs/obsidian/lexer/Token.scala
- src/main/scala/edu/cmu/cs/obsidian/parser/AST.scala
- src/main/scala/edu/cmu/cs/obsidian/parser/Parser.scala
- src/main/scala/edu/cmu/cs/obsidian/typecheck/Checker.scala
- src/main/scala/edu/cmu/cs/obsidian/util/IdentityAstTransformer.scala
- src/test/scala/edu/cmu/cs/obsidian/tests/ParserTests.scala
We can now write things like `int x = a % b;`, which compiles to the existing `BigInteger` method `mod`.
This closes #238.
> Add support for mod operator

- resources/tests/type_checker_tests/InterfaceWithReturn.obs
- src/main/scala/edu/cmu/cs/obsidian/typecheck/Checker.scala
- src/test/scala/edu/cmu/cs/obsidian/tests/TypeCheckerTests.scala
In the case of interfaces, we should not require that methods be checked for a return statement. This fix simply ignores this check if the contract containing the transaction is an interface.
This closes #240.
> Remove erroneous return statement check on interface transactions

- README.md
- network-framework/scripts/install.sh
- network-framework/scripts/instantiate.sh
- network-framework/scripts/invoke.sh
- network-framework/scripts/upgrade.sh
- network-framework/upgrade.sh
This pull request adds a new script, `upgrade.sh`, which can be used to upgrade the chaincode on a running Fabric network (i.e., replace the old code without destroying and recreating the whole network). To use it, ensure that there is a running Fabric network, then run `./upgrade.sh`.
This brings the time to test code changes down to about 40 seconds. Not sure how to further improve, other than reducing the delay at the end of the scripts (would shave off about 9 more seconds), but as I'm not even sure why that's there, I don't want to mess with it too much.
> Enable chaincode upgrades without recreating network

- src/main/scala/edu/cmu/cs/obsidian/typecheck/Checker.scala
The bug was that, when typechecking LogicalNegation, the code simply asserted that the expression being negated was a boolean, without rewrapping it in the LogicalNegation.
This closes #251.
> Fix unwrapping of LogicalNegation in typechecker

- resources/tests/compilerTests/MultipleConstructorGroup.obs
- src/main/scala/edu/cmu/cs/obsidian/codegen/CodeGen.scala
- src/test/scala/edu/cmu/cs/obsidian/tests/CompilerTests.scala
This pull requests modifies the old constructor code generation by simply checking if the field `constructorReturnsOwnedReference` or related method exists before creating it, thereby preventing its duplication. 
This closes #253.
> Fix duplicate field/method generation for constructors

- bin/obsidianc
- src/main/scala/edu/cmu/cs/obsidian/Main.scala
Changes as discussed:
- Build script can work from any directory
- Will automatically build jar if it does not exist
- Can pass compiler flags in addition to file path now
> Improve build script to work from any directory

- resources/tests/type_checker_tests/AssetStateTracking.obs
- resources/tests/type_checker_tests/AssetStateTrackingOkay.obs
- src/main/scala/edu/cmu/cs/obsidian/typecheck/Checker.scala
- src/main/scala/edu/cmu/cs/obsidian/typecheck/ObsidianType.scala
- src/test/scala/edu/cmu/cs/obsidian/tests/TypeCheckerTests.scala
Owned references to contracts that have asset states are now properly treated as though they may be assets.
This closes #256.
> Give error when asset state reference is lost

- bin/obsidianc
The new script will search the `target/` directory for `obsidianc.jar`, and use the first one it finds. This approach, unlike hardcoding the version into the path, should work with any version of Scala.
> Fix obsidianc so it works with any Scala version

- .idea/modules.xml
- .idea/scala_compiler.xml
- resources/tests/GanacheTests/IfThenElse.json
- resources/tests/GanacheTests/IfThenElse.obs
- src/main/scala/edu/cmu/cs/obsidian/codegen/CodeGenYul.scala
This implements translation of if-then-else to switch per #308, I think, but really shows that the problem in #310 is important to fix right away. Specifically, when translating the test case
```
main contract IfThenElse{
int x;
transaction ifthenelse() {
if (true) {
x = 1;
} else {
x = 0;
}
return;
}
}
```
we actually produce the expansion
```
List(Switch(Literal(boolean,true,bool),List(Case(Literal(boolean,true,bool),Block(List(ExpressionStatement(FunctionCall(Identifier(sstore),List(Literal(number,0,int), Literal(number,1,int))))))), Case(Literal(boolean,false,bool),Block(List(ExpressionStatement(FunctionCall(Identifier(sstore),List(Literal(number,0,int), Literal(number,0,int))))))))))
```
but the written file is
```
object "IfThenElse" {
code {
mstore(64,128)
return(0,0)
}
object …
```
> adding translation for if-then-else, some code hoisting for clarity

- README.md
The Travis repository has already been migrated to the .com domain,
all that remains is to update this link.
In general, this change as announced by Travis in May 2018:
https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/
> Update Travis link to use .com domain

- resources/tests/GanacheTests/AssignLocalAdd.json
- resources/tests/GanacheTests/AssignLocalAdd.obs
- resources/tests/GanacheTests/BoolLiteral.obs
- resources/tests/GanacheTests/If.json
- resources/tests/GanacheTests/If.obs
- resources/tests/GanacheTests/IfThenElse.obs
- resources/tests/GanacheTests/IntConst.obs
- resources/tests/GanacheTests/PrimOps.obs
- resources/tests/GanacheTests/SimpleCall.obs
- src/main/scala/edu/cmu/cs/obsidian/codegen/CodeGenYul.scala
- src/main/scala/edu/cmu/cs/obsidian/codegen/Util.scala
- src/main/scala/edu/cmu/cs/obsidian/codegen/yulAST.scala
this PR includes:
* assigning to local variables
* string literals
* if statements without and else
* a bug fix for if-then-else
* fixing a bug that made it look like fields worked when they did not
* changing the test cases to use local variables not fields
* declaring local variables
this would at least partially address #328 and #320
we now also emit code for `PrimOps.obs` that looks plausible, but `solc` produces this error when run on it:
```
Exception while assembling: /solidity/libyul/backends/evm/EVMObjectCompiler.cpp(66): Throw in function void solidity::yul::EVMObjectCompiler::run(solidity::yul::Object&, bool)
Dynamic exception type: boost::wrapexcept<solidity::yul::StackTooDeepError>
std::exception::what: Variable x is 1 slot(s) too deep inside the stack. …
```
> assignments, local variables, better tests, other bug fixes

- bin/2sc.py
- resources/tests/GanacheTests/PrimOpsSubNeg.json
- travis_specific/ganache_tests.sh
this closes #338. it also updates the list of tests that are written but don't pass in https://github.com/mcoblenz/Obsidian/issues/335 and makes fixing the parser the only thing left to do for https://github.com/mcoblenz/Obsidian/issues/337.
> add support for tests that produce negative numbers

- Obsidian_Runtime/src/main/yul_templates/object.mustache
- src/main/scala/edu/cmu/cs/obsidian/codegen/CodeGenYul.scala
- src/main/scala/edu/cmu/cs/obsidian/codegen/yulAST.scala
This make a flat Yul object with updated transactions from child contracts. Fields are still stored in storage, not memory, and I'm not sure about the treatment of this in the dispatch table.
> generate flat yul object from child contracts

- src/main/scala/edu/cmu/cs/obsidian/codegen/CodeGen.scala
- src/main/scala/edu/cmu/cs/obsidian/codegen/CodeGenYul.scala
- src/main/scala/edu/cmu/cs/obsidian/parser/AST.scala
- src/main/scala/edu/cmu/cs/obsidian/parser/Parser.scala
- src/main/scala/edu/cmu/cs/obsidian/typecheck/Checker.scala
- src/main/scala/edu/cmu/cs/obsidian/util/IdentityAstTransformer.scala
- src/test/scala/edu/cmu/cs/obsidian/tests/TypeCheckerTests.scala
this addresses #373. i added a field to the expression nodes of the AST to store their type as its computed so that it's then available to yul code generation. this meant making changes also to the parser and test cases, as well as a few other things, to reflect the different signatures for the relevant expressions.
right now this passes the typechecker tests; i am not at all confident that it's perfectly correct, but I think i need to use it to see what's broken and then fix those errors once they come up.
i have left comments where I was least sure about what I was doing. hopefully that will make the errors easier to find, or maybe some of them can get caught in review before they get merged.
> memoize type info

- src/main/scala/edu/cmu/cs/obsidian/Main.scala
- src/main/scala/edu/cmu/cs/obsidian/codegen/CodeGenYul.scala
- src/main/scala/edu/cmu/cs/obsidian/codegen/ParserUtil.scala
- src/main/scala/edu/cmu/cs/obsidian/codegen/Util.scala
- src/main/scala/edu/cmu/cs/obsidian/codegen/yulAST.scala
- src/main/scala/edu/cmu/cs/obsidian/typecheck/Checker.scala
- src/main/scala/edu/cmu/cs/obsidian/util/IdentityAstTransformer.scala
This addresses #373! We use the type annotations in the expression ASTs to smooth out the translations and remove a fair few hacks.
There are a couple of loose ends:
1. The `This` AST node constructor now takes a type argument. There are two places in `Checker.scala` that I don't know what to put there other than `None` because there aren't any obsidian types in the (scala) context at that time. @mcoblenz, do you know? I've noted them in the review below; there's another one on `Checker.scala:2705` that I think is more benign because that's already kind of a hack so it makes sense that it doesn't make sense.
2. This PR passes all the GanacheTests and almost all of the tests in the larger test suite, but not all the typechecker tests (shown below). So I must have broken something. The …
> use type annotations in Yul codegen

- resources/tests/GanacheTests/PrimOpsNeg.json
- src/main/scala/edu/cmu/cs/obsidian/typecheck/Checker.scala
The negation expression of check and infer dropped the negation around the expression before returning it, which caused the test to fail in https://github.com/mcoblenz/Obsidian/issues/337. This PR fixes that. The issue originally identified this as a parser issue, but with some digging in the debugger, I saw that it came out of the parser fine but the AST was getting mangled while being type checked.
> fixing checkAndInfer for negation

- bin/skipped_tests.sh
- resources/tests/GanacheTests/SG.json
- resources/tests/GanacheTests/SG.obs
- resources/tests/GanacheTests/SGTwoContainers.json
- resources/tests/GanacheTests/SGTwoContainers.obs
- resources/tests/GanacheTests/SetGetNoArgs.obs
- resources/tests/GanacheTests/SetGetNoArgsNoConstruct.obs
- src/main/scala/edu/cmu/cs/obsidian/codegen/CodeGenYul.scala
- src/main/scala/edu/cmu/cs/obsidian/codegen/ParserUtil.scala
- src/main/scala/edu/cmu/cs/obsidian/codegen/Util.scala
- src/main/scala/edu/cmu/cs/obsidian/codegen/yulAST.scala
- src/test/scala/edu/cmu/cs/obsidian/codegen/UtilTest.scala
- travis_specific/ganache_tests.sh
this addresses #371 and #372. These tests pass:
- https://github.com/mcoblenz/Obsidian/blob/flat_offsets/resources/tests/GanacheTests/SG.obs
- https://github.com/mcoblenz/Obsidian/blob/flat_offsets/resources/tests/GanacheTests/SetGetNoArgsNoConstruct.obs
- https://github.com/mcoblenz/Obsidian/blob/flat_offsets/resources/tests/GanacheTests/SetGetNoArgsNoConstructNoInit.obs
These do not:
- https://github.com/mcoblenz/Obsidian/blob/flat_offsets/resources/tests/GanacheTests/SetGet.obs fails because the entry for the set function that takes an argument in the dispatch table has a free variable in it; this is documented in https://github.com/mcoblenz/Obsidian/issues/370 but I'm not quite sure how to fix it.
- https://github.com/mcoblenz/Obsidian/blob/flat_offsets/resources/tests/GanacheTests/Set …
> compute offsets, store fields in memory

- Obsidian_Runtime/src/main/yul_templates/object.mustache
- bin/run_any_yul.sh
- resources/tests/GanacheTests/SetGetPointer.json
- resources/tests/GanacheTests/SetGetPointer.obs
- src/main/scala/edu/cmu/cs/obsidian/codegen/CodeGenYul.scala
- src/main/scala/edu/cmu/cs/obsidian/codegen/Util.scala
- src/main/scala/edu/cmu/cs/obsidian/codegen/yulAST.scala
- src/test/scala/edu/cmu/cs/obsidian/codegen/UtilTest.scala
This closes #393, #392, #391, and #389. It partially addresses #370; I think that everything in the main contract will end up in the dispatch table now, even if it's private.
One worry is that the code in `YulObject` assumes that the `Seq[YulStatement]` passed contains only function declaration objects -- this is made explicit by a use of `.asInstaceOf`. That happens to be true right now, but won't be forever I think. I'm OK with this bit of technical debt for now, but, @mcoblenz, you may not be. 
Once this is approved and merged into `flat_alloc`, I'll do a merge into master as well because I think this is a stand alone feature update as well as being on the way to allocation.
> allocate fields with pointers, rewrite yulobject and mustache interaction to reflect current object layout

- src/main/scala/edu/cmu/cs/obsidian/codegen/CodeGenYul.scala
- src/main/scala/edu/cmu/cs/obsidian/codegen/Util.scala
- src/main/scala/edu/cmu/cs/obsidian/codegen/yulAST.scala
previously we reused the obsidian types for yul types, which worked but was messy and forced some stringly typed programming. this is a little bit neater, imo.
@mcoblenz when reviewing, please feel free to suggest better names for constructors and that sort of detail; i'm not positive this meshes that well with the codebase but i think the idea is good.
> adding a case class for yul types

- resources/tests/GanacheTests/SetGetConstructorField.obs
- resources/tests/GanacheTests/tests.json
- src/main/scala/edu/cmu/cs/obsidian/codegen/CodeGenYul.scala
- src/main/scala/edu/cmu/cs/obsidian/codegen/yulAST.scala
- we now emit a tracer for every contract in the program, not just the ones that happen to be used in fields in the main contract
- we call the tracer for a contract after it's constructed
- the tracers copy the fields to storage, for now at the same address that they appear in memory
- the tracers emit logs as they do this, but the values emitted are not that meaningful
upcoming changes not included in this PR:
- write meaningful values to the logs
- use those logged values to verify that fields are being written to storage
- write to addresses in storage that are above some thresh hold value, so we can tell which addresses are in memory and which are in storage.
> call tracers after every constructor call

- resources/tests/GanacheTests/tests.json
- src/main/scala/edu/cmu/cs/obsidian/codegen/CodeGenYul.scala
In the test `SetGetLogs`, we emit tracers for both contracts but the code only contains calls to the constructor for `IntContainer`. That happens three times, so we expect three things to be written to the log. At the time that the constructor is called, the field has not been initialized so I would expect those three things to all be `0`. However, we emit `0,224,224` not `0,0,0`.  I don't know where the number `224` is coming from and I'm not sure if it's right or not.
The test `SetGetConstructorField` emits `0,0,0` to the logs. This seems like the right output behaviour because the tracers are getting called only after constructor applications, which again means that the fields should be unset and cold reads to unset addresses should produce `0`. We get them three times even though …
> log contents of fields as written to storage after constructor calls
